### PR TITLE
Fixes #51

### LINKED ISSUE #51: After server protocol changed, app crashes on list request
WiFi was turned on, but there was no internet connection.
After that a connection was established.
The app crashed with

2-24 09:17:13.485 14928-16675/? E/AndroidRuntime: FATAL EXCEPTION: IntentService[FetchService]
                                                   Process: org.imozerov.streetartview, PID: 14928
                                                   java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
                                                       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                       at java.util.ArrayList.get(ArrayList.java:308)
                                                       at org.imozerov.streetartview.storage.model.ExtensionsKt.copyDataFromJson(Extensions.kt:13)
                                                       at org.imozerov.streetartview.storage.DataSource.insert(DataSource.kt:30)
                                                       at org.imozerov.streetartview.network.FetchService.handleStartFetchAction(FetchService.kt:43)
                                                       at org.imozerov.streetartview.network.FetchService.onHandleIntent(FetchService.kt:27)
                                                       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:145)
                                                       at android.os.HandlerThread.run(HandlerThread.java:61)

### PR DESCRIPTION
**Pull request by genaforvena**
Migrated models to match server's

### CODE REVIEW

**Comment by genaforvena** [comment]
@sanovikov71

**Comment by genaforvena** [comment]
@oleg-popenov

File: app/src/main/java/org/imozerov/streetartview/storage/DataSource.kt [hunk 1]
```diff
@@ -73,19 +69,28 @@ class DataSource(private val realm: Realm, private val handler: Handler) {
         with (realmAuthor) {
             id = SystemClock.currentThreadTimeMillis().toString()
             name = "${randomFrom(names)} ${randomFrom(lastNames)}"
-            description = "The best artist in the world"
+            photo = "The best artist in the world"
```
Comment (sanovikov71) [inline app/src/main/java/org/imozerov/streetartview/storage/DataSource.kt]: What is it? Looks strange

File: app/src/main/java/org/imozerov/streetartview/storage/DataSource.kt [hunk 2]
```diff
@@ -73,19 +69,28 @@ class DataSource(private val realm: Realm, private val handler: Handler) {
...
+        with(realmLocation) {
+            address = "Some address, 34"
+            lat = getRandomBetween(56.26, 56.33)
+            lng = getRandomBetween(43.86, 44.05)
         }
 
         val realmArtObject = RealmArtObject()
         with (realmArtObject) {
-            author = realmAuthor
+            authors = realmAuthors
```
Comment (sanovikov71) [inline app/src/main/java/org/imozerov/streetartview/storage/DataSource.kt:87]: Does it mean that now several authors can correspond to an art object in our model?

File: app/src/main/java/org/imozerov/streetartview/storage/model/RealmLocation.java [hunk 3]
```diff
@@ -0,0 +1,36 @@
+package org.imozerov.streetartview.storage.model;
```
Comment (sanovikov71) [inline app/src/main/java/org/imozerov/streetartview/storage/model/RealmLocation.java:1]: Do we really need this object? Maybe it is simpler not to create to many entities, as it can be just two fields in a art object

**Comment by sanovikov71** [comment]
-1 :)

File: app/src/main/java/org/imozerov/streetartview/storage/DataSource.kt (hunk 1 above)
Comment (genaforvena) [inline app/src/main/java/org/imozerov/streetartview/storage/DataSource.kt]: I'll fix it.

File: app/src/main/java/org/imozerov/streetartview/storage/DataSource.kt (hunk 2 above)
Comment (genaforvena) [inline app/src/main/java/org/imozerov/streetartview/storage/DataSource.kt:87]: Yes

File: app/src/main/java/org/imozerov/streetartview/storage/model/RealmLocation.java (hunk 3 above)
Comment (genaforvena) [inline app/src/main/java/org/imozerov/streetartview/storage/model/RealmLocation.java:1]: This gives us some sort of modularity. I'll keep this class.
